### ISSUE TITLE
Zombienet feature walk-through and demonstration

### ISSUE THREAD

**Issue by coax1d** [substrate-developer-hub/substrate-seminar#1]
Hi,

I know zombienet is relatively new and would love if there could be a seminar regarding using this cool new feature for testing parachains!

**Comment by sacha-l** [comment]
This is a great topic for seminar, yes. I think the team working on this at Parity (https://github.com/paritytech/zombienet) is still preparing things to make it easy for teams to use it. 

I'll keep this issue open and get back here once the authors of the Zombienet repo release a version ready to be presented on seminar.

**Comment by coax1d** [comment]
Great!!! Thank you Sacha!!

**Comment by sacha-l** [comment]
Close in favour of #23.
