### ISSUE TITLE
A multi-bridge router bridging Dotsama and other ecosystems

### ISSUE THREAD

**Issue by tolak** [substrate-developer-hub/substrate-seminar#11]
## Title

A multi-bridge router bridging Dotsama and other ecosystems

## Description

SubBridge is a multi-bridge router dedicate to connect the Polkadot parachains and other ecosystems. By first integrating two popular bridge solutions, i.e., ChainBridge and CelerBridge, it connects Dotsama and EVM ecosystems, and will bridge more ecosystems in the future.

![](https://i.imgur.com/jDBacn1.png)

The core of SubBridge is two-fold: 1) it uses common interfaces to represent different blockchains and the assets on them, which makes it a "bridge hub" and able to integrate different bridges; and 2) it designs an asset router across bridges, which means it can forward assets from one bridge to another to achieve the cross-chain transfer even if there is no direct bridge.

As its first version, SubBridge chooses to integrate XcmBridge (a bridge between parachains) and ChainBridge (a bridge between Khala network and other EVM chains). It utilizes the `MultiLocation` concept introduced by XCM protocol to represent the cross-chain route path. By implementing a bridge router, SubBridge can forward transfer from one bridge to other bridge. That means users can transfer assets from parachains to EVM chains directly, and vice versa.

So far with SubBridge, people can transfer assets between:

- Khala <-> Parachians
- Khala <-> EVM chains
- **Parachains <-> EVM chains**

## Plan

- Integrate CelerBridge [WIP]
- Upgrade ChainBridge to V2
- Upgrade XCM to V3

## Relevant material

[SubBridge Tech Talk Slide](https://docs.google.com/presentation/d/1BpcSxCA8kyA5oU75mzkh-Om6rbu5EOIQy9V2Ged4lXg/edit?usp=sharing)

[SubBridge Wiki](https://wiki.phala.network/en-us/general/subbridge/intro/)

**Comment by tolak** [comment]
On this talk, we are going to talk the following topics:

- What is SubBridge
- Why we build it
- Implementation of SubBridge, e.g. router, spec desgn
- How to integrate your assets into SubBridge
- Further development plan

Feel free to add more topics that you are interested in.

**Comment by sacha-l** [comment]
@tolak thanks for detailing the seminar topic proposal ! I think this would be a killer topic to have on seminar for sure. Is this related to #9 ?

**Comment by tolak** [comment]
@sacha-l #9 seems to focus on how XCM should export to the smart contract, here we more like to focus on how we expand(or connect) XCM to other bridges.

**Comment by sacha-l** [comment]
👍🏻 - how does May 24th sound to you (@3PM CET) ? 📆

**Comment by tolak** [comment]
> 👍🏻 - how does May 24th sound to you (@3PM CET) ? 📆 

It's very good to me!
