### ISSUE TITLE
Subsquid: an open, permissive and decentralized indexing framework for Substrate and EVM

### ISSUE THREAD

**Issue by RaekwonIII** [substrate-developer-hub/substrate-seminar#14]
## Background

Subsquid is developing an indexing framework, composed of a network of Squid Archives and an SDK to develop lightweight APIs on top of them, to implement arbitrary business logic and process on-chain data. This is to provide Web3 DApps with the necessary middleware to power them and feed data to them.

## Seminar

The seminar will be an introduction to Subsquid, its guiding principles and fundamentals, and a code walkthrough on how to customize the provided template to fulfill a particular need, touching on key aspects and what needs to be changed to obtain the expected result.

**Comment by sacha-l** [comment]
Hey @RaekwonIII - great topic. Could you provide some resources for others to be able to learn more about Subsquid (Github repos, docs, website, anything else) ? 

l would be interested in turning this into an opportunity to understand the needs of current and future developers using the template and demo some apps using it. It's not entirely clear to me who your target users are but it would be great to reach out to some front-end developers and invite them to the seminar for them to learn how they can easily build front-end apps  that query blockchain data using Subsquid - or integrate Subsquid into existing DApps. 

A lot of developers (both web3 and not) would love to learn more about Subsquid, let's make this happen!

**Comment by sacha-l** [comment]
@RaekwonIII: How does June 21st work for you - Tuesday, 3PM CET?

**Comment by kukabi** [comment]
I'm looking forward to this seminar. @RaekwonIII I've been hearing about Subsquid but I'm starting to experiment with it just now, the documentation is neat ⭐  I might add more ideas/comments for the seminar as I discover the framework, but some info on how Subsquid compares to the other indexing solutions (Sidecar, Subquery) in the Substrate ecosystem would be just great, maybe also the advantages/disadvantages of using an indexing solution compared to a chain data API. Thanks!

**Comment by sacha-l** [comment]
@RaekwonIII: could you provide more details so that I can finalize the schedule  and add this to [this folder](https://github.com/substrate-developer-hub/substrate-seminar/tree/main/scheduled/2022) (please fill in the blanks) :

## Title

Subsquid: an open, permissive and decentralized indexing framework for Substrate and EVM

## Description

The seminar will be an introduction to Subsquid, its guiding principles and fundamentals, and a code walkthrough on how to customize the provided template to fulfill a particular need, touching on key aspects and what needs to be changed to obtain the expected result.

## Plan

_(i.e. just the outline of the content of your seminar)_

## Links and resources 

_(e.g. if you have a deck; repos where this work exists; related material; complimentary readings etc.)_

Thanks!

**Comment by RaekwonIII** [comment]
### Title
Subsquid: an open, permissive and decentralized indexing framework for Substrate and EVM

### Description
The seminar will be an introduction to Subsquid, its guiding principles and fundamentals, and a code walkthrough on how to customize the provided template to fulfill a particular need, touching on key aspects and what needs to be changed to obtain the expected result.

### Plan

- Blockchain indexing and why it matters
- Introduction to Subsquid and its proposed solution
- Focus on Subsquid's key features
- Hands-on demo, going over the steps to customize a Squid API project

### Links and resources

This is [a demo deck](https://hackmd.io/@RaekwonIII/Moonbeam-workshop) I used for a different workshop, I have not prepared one for this seminar, I might make a few changes.

- [Subsquid docs](https://docs.subsquid.io/)
- [Subsquid main GitHub repo](https://github.com/subsquid/squid) and [template repository](https://github.com/subsquid/squid-template), which is the starting point for developers.
- [Subsquid website](https://subsquid.io/) which also offers a [service to host APIs](https://app.subsquid.io/aquarium) created with our SDK
- a couple of examples showing how the SDK can be used:
  - [Crust example](https://github.com/subsquid/squid-crust-example) featured in [this Tutorial](https://docs.subsquid.io/tutorial/create-a-simple-squid) in the docs
  - A [Polkadot Treasury Proposals explorer](https://github.com/subsquid/squid-polkadot-treasury-example)
  - An [example showcasing the support for external APIs calls](https://github.com/subsquid/squid-external-api-example) while processing on-chain data (featuring CoinGecko)
