### ISSUE TITLE
Flame logo

### ISSUE THREAD

**Issue by Carrussalgreencompany** [substrate-developer-hub/substrate-seminar#18]
### Title

Flame logo on the substrate polkadot Parachain

### Description

Build for ecosystem and nft transaction

### Topic

Flame logo

### Plan

Work in progress - pending verification

### Links and resources

Parity.io

**Comment by sacha-l** [comment]
Hi @Carrussalgreencompany - could you please resubmit your proposal, adding more context and information. Thank you.
