### ISSUE TITLE
[Topic Proposal]: Build a social oracle with ink! on Phala

### ISSUE THREAD

**Issue by h4x3rotab** [substrate-developer-hub/substrate-seminar#20]
### Title

Build a social oracle with ink! on Phala

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Intermediate

### Description

In this workshop, you are going to play with the oracle built on Phala Fat Contract, and learn how to build an oracle that:

1. links off-chain identity to blockchain
2. sends http requests to verify off-chain data
3. gives out [POAP NFT](https://poap.xyz/) rewards
4. is written in [ink!](https://ink.substrate.io/)
5. (and can be build in 15 mins)

### Topic

ink, oracle, socialfi, offchain computation, offchain attestation

### Plan

- Part 1: Demo - The Easy Challenge
   - How the oracle works
   - Try the prebuilt oracle contract
   - Get a POAP NFT
- Part 2: Breakdown of the oracle implementation in ink!
   - Ink basics: storage, transactions, and queries
   - Github account verification
   - HTTP requests in Fat Contract
   - Offchain attestation
- Part 3: Deploy your own oracle - The Advanced Challenge
   - Compile a Fat Contract
   - Interact with it on Contract UI

### Links and resources

- [Workshop tutorial](https://github.com/Phala-Network/oracle-workshop)
- [Workshop DApp](https://phala-decoded-2022.netlify.app/)
- [Fat Contract UI](https://phat.phala.network/)

**Comment by sacha-l** [comment]
Hey @h4x3rotab - everything looks good to me. How does Tuesday September 27th work for you?

**Comment by h4x3rotab** [comment]
Sounds good!

**Comment by sacha-l** [comment]
I think we should update this to the workshop Joshua did at sub0. Will close, awaiting a new topic submission.
