### ISSUE TITLE
[Topic Proposal]: Demystifying Macro Magic

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-seminar#21]
### Title

Demystifying Macro Magic

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Intermediate

### Description

This seminar will uncover what really happens when the `construct_runtime` is called as well as other FRAME macros.

### Topic

FRAME macros

### Plan

This is WIP but here's the basic idea:

1. Go over the basic flow of how a FRAME pallet gets passed into the `contstruct_runtime` macro, what the macros expects and what high level view of the build cycle for the Wasm runtime looks like.
2. Look into the Outer Call Enum using `cargo expand` and explain how this gets used by the Executive module.
3. Do some more looking into `cargo expand` stuff 

### Links and resources

- [FRAME Macros](https://docs.substrate.io/reference/frame-macros/)
- [`cargo expand`](https://github.com/dtolnay/cargo-expand)

**Comment by sam0x17** [comment]
My general plan is to explain the high level of how FRAME pallet macro parsing and expansion works through the lens of implementing a simple pallet macro (most likely `#[pallet::whitelist_storage]`), which was the first macro-related substrate I tackled when I was new to the ecosystem.

This will likely include:
1. a brief overview of what pallet macros are and where they are used
2. a quick description of the `whitelist_storage` macro, what it is supposed to do, and why it should exist
3. a general discussion about the "outer macro" pattern
4. going through the steps of implementing the `whitelist_storage` macro as a way of explaining how pallet macros are parsed and expanded

Time permitting I may also go over:
* how pallet macros are tested

**Comment by weezy20** [comment]
Suggestion: Please also go through the extra parameters that go into `construct_runtime!` such as `Block`, `NodeBlock` and `UncheckedExtrinsic` which is defined as : 
```rust 
pub type UncheckedExtrinsic =
	generic::UncheckedExtrinsic<Address, RuntimeCall, Signature, SignedExtra>;
```
This is important in including the signed extensions into the runtime for later tx validation.
