### ISSUE TITLE
[Topic Proposal]: SubQuery

### ISSUE THREAD

**Issue by jamesbayly** [substrate-developer-hub/substrate-seminar#24]
### Title

Indexing Multiple Polkadot chains with SubQuery 

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Low, intro level

### Description

Learn how to build the next game changing dApp faster with SubQuery. Our open, fast, flexible, and unified indexer powers some of the biggest projects and dApps in Substrate, Avalanche, Cosmos, and Algorand.

In this seminar, we will walk through a brand new feature that allows you to index data from multiple Polkadot parachains into a single SubQuery dataset. This allows you to build more engaging cross-chain dApps on Polkadot that work across over 70 parachains with minimal effort.

### Topic

blockchain indexing, dApp development

### Plan

In this seminar we're going to dive deep into our architecture and philosophy, then build a basic project live together:

- We'll explain how SubQuery works and why you'll want to use if for your next project
- We'll explain the design philosophy behind it and how we work to build the best data provider possible
- We'll walk through the process of creating a new project and API for your app
- We'll walk through a more complicated example that shows off how to index data across multiple Polkadot networks
- We'll take a look at the different hosting services in SubQuery with the Managed service and Network

### Links and resources

- [Demo deck for this Seminar](https://docs.google.com/presentation/d/1RQnAxV1qk_YtqoXbI7n0U-DH5Osmt2w6xHzewIoxI9s/edit?usp=sharing)
  - We use two example projects during this demo
  - The first one is a simple project that indexes all transfers in Polkadot https://github.com/jamesbayly/subql_transfers
  - The second is a more complex project that indexes transfers from across different Polkadot para/relaychains https://github.com/subquery/multi-networks-transfers
- [SubQuery Documentation](https://academy.subquery.network/) including 
  - [Quick start guides](https://academy.subquery.network/quickstart/quickstart.html)
  - [Technical documentation](https://academy.subquery.network/build/introduction.html)
  - [Multi-chain indexing](https://academy.subquery.network/build/multi-chain.html)
  - [Guides on how to run your projects](https://academy.subquery.network/run_publish/run.html)
- [SubQuery Explorer](explorer.subquery.network/) is our hosting provider with a generour free tier. It also shows off hundreds of live examples from other teams around the ecosystem
- [SubQuery GitHub](https://github.com/subquery/subql)

**Comment by sacha-l** [comment]
@jamesbayly is this good to go as is? please make sure to update all relevant links and resources, cheers!

**Comment by jamesbayly** [comment]
Good to go
