### ISSUE TITLE
[Topic Request]: Subalfred the new fork-off

### ISSUE THREAD

**Issue by flipchan** [substrate-developer-hub/substrate-seminar#25]
### Description

Hey,

As fork-off-substrate has not been maintained in a while, it would be nice to have a seminar about subalfred(https://github.com/hack-ink/subalfred/) it's a pretty new tool but very useful for substrate based chains that have metadata 14 or later. Plus it's written  rust(currently only  supports nightly) and is not old node.js code which fork-off is.

Would be great to have a seminar about Subalfred! I find it a really useful tool when testing runtime upgrades.

### Topic

runtime migrations, new substrate tool

### Additional information

I think its a really useful tool that more developers should be aware of as it's super useful.

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Intermediate

**Comment by sacha-l** [comment]
Hey @flipchan - I'm coordinating with @AurevoirXavier to schedule this. Is there any specific SubAlfred utility you'd like to see in action? Runtime upgrades is a good one, anything else? Cheers!

**Comment by flipchan** [comment]
Cool @sacha-l! 
Some ideas:  
*  runtime upgrades   
*  forking live chains/rewriting a chainspec with alice keys
*  Quering for pallet prefixes
*   Supporting older versions of substrate chains that does not yet have metadata V14(maybe a bit out of scope)   

These ideas come to mind rn.

**Comment by AurevoirXavier** [comment]
> * Supporting older versions of substrate chains that does not yet have metadata V14(maybe a bit out of scope)

Except for this one. Others LGTM.
