### ISSUE TITLE
[Topic Proposal]: Metaverse standardization

### ISSUE THREAD

**Issue by LastSymbol0** [substrate-developer-hub/substrate-seminar#26]
### Title

Metaverse standardization and implementation with Substrate

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Begginer-friendly

### Description

I would like to present how Asylum's vision of the Metaverse can be implemented using Polkadot, the role of standardization of the Metaverse. How is interoperability can be fundamentally implemented using Substrate, and how it will be shown in gaming.

### Topic

Polkadot for Metaverse. Pallet development. Interoperable NFT. DAO architecture.

### Plan

Intro: why Metaverse can not exist without interoperability.
1. Why Polkadot is the right solution for Metaverse projects. Parachains, Shared State, and XCM possibilities.
2. Multi-resource NFTs. How to use them to create an Avatar and game items with different displays. One NFT in 2D and 3D.
3. NFTs semantics. How to create item interpretations and give them semantics. How game clients will handle such NFTs.
2. Gaming parachain. Example.
5. DAO Architecture. Example.
6. How to apply XCM to transfer NFT items within gaming parachains.

### Links and resources

https://gitlab.com/asylum-space/asylum-ui
https://gitlab.com/asylum-space/asylum-item-nft
https://gitlab.com/asylum-space/imp

**Comment by sacha-l** [comment]
I love the topic proposal, thank you. It would be great if this could become a learning resource for someone looking to make their own multi-resource NFT and learn about their capabilities. 

I think these two points will be key:

> How to create item interpretations and give them semantics. How game clients will handle such NFTs.
> How to apply XCM to transfer NFT items within gaming parachains.

I see this seminar being valuable in two ways:
* presenting the unique opportunities for building NFT applications on Polkadot 
* presenting ways UX/UI developers can leverage the rich metadata of these NFTs in different ways 

Let's make this happen -- please [dm me](@sacha-l:matrix.parity.io) to schedule something.

**Comment by sacha-l** [comment]
Are you still interesting in presenting this topic @LastSymbol0 ?

**Comment by sacha-l** [comment]
Ping 👼🏻  cc @LastSymbol0
