### ISSUE TITLE
[Topic Proposal]: ink! 4.0 Release Online Event

### ISSUE THREAD

**Issue by PierreOssun** [substrate-developer-hub/substrate-seminar#27]
### Title

ink! 4.0 Release Online Event

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Knowledge about ink! is prefered.

### Description

Hi there!
ink! 4.0 is coming in some weeks and will add a lot of new feature:
- new storage rework to reduce size of contract
- new metadata taht will simply versioning and allow contract verification
- new integration tests 
- fixed Events
- ..

It will be a big day for our ecosystem. I think It can be great to host an event to talk about it with Parity / Supercolony and us Astar.
The goal is to share new ink! features of this release and for Supercolony & us to share our latest news from our WASM tools & networks.
It targets an audience that wants to know the lastest news of ink! development

### Topic

#smart-contract #ink! 

### Plan

As this seminar will include three different parties (Parity, Supercolony, Astar) I think everybody will prepare its own small presentation on his side. But basically, it can be:
20~ mins from Parity talking about ink!
10 - 20~ mins for Supercolony
10 - 20~ mins for Astar
10 mins for some Q&A if needed

**Comment by sacha-l** [comment]
Would love to support this on Seminar for sure. Perhaps we can bring in ideas from [this forum thread](https://forum.polkadot.network/t/we-need-to-make-ink-showcase-projects/592) too.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/we-need-to-make-ink-showcase-projects/592/17

**Comment by sacha-l** [comment]
@PierreOssun : any update on timelines for this?
