### ISSUE TITLE
[Topic Proposal]: Using Brushfam tools to ease ink! development

### ISSUE THREAD

**Issue by coreggon11** [substrate-developer-hub/substrate-seminar#35]
### Title

Using Brushfam tools to ease ink! development

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Beginner friendly, Intermediate

### Description

Brushfam maintains critical tools for the ink! smart contract ecosystem, which serve the purpose of easing ink! smart contract development. These tools are widely used and known by the ink! community. We would like to introduce these tools for those who don't know about them yet, while also showcasing some development using these tools and answering potential questions. The tools we would mention are 
* OpenBrush: ink! smart contract library to ease the development of ink! contracts
* Typechain-polkadot: typescript wrapper around ink! smart contracts which can be used either in UI or typescript integration tests
* Sol2Ink: tool for easy migration from Solidity to ink!

### Topic

ink! smart contract development, openbrush

### Plan

* Introduction to Brushfam tools
* Easy migration from Solidity to ink! using Sol2Ink
  * Convert a Solidity smart contract to an ink! smart contract using Sol2Ink
* Utilizing OpenBrush macros and utilities in ink! smart contract development
  * Extend the smart contract generated in the previous part by some useful utilities
  * Create a new ink! smart contract utilizing OpenBrush
* Creating integration tests for ink! contracts using Typechain-Polkadot
  * Showcase how to test the previously generated contracts using Typechain-Polkadot. Reproducing these steps will also be useful for UI development

### Links and resources

https://github.com/727-Ventures/openbrush-contracts
https://github.com/727-Ventures/typechain-polkadot
https://github.com/727-Ventures/sol2ink

**Comment by sacha-l** [comment]
Thanks for posting this request! Plan sounds good to me. Looping in @SkymanOne who may have some topic requests the ink! team may like you to cover. 

How does Jan 31st 4pm CET work for you?

**Comment by SkymanOne** [comment]
Thanks @sacha-l for pinging me. One of the ideas that have been circulating within ink! the team is to create a series of tutorials on how to build full stack dApp using ink! and its tools 

So, It would be a good idea to centre the seminar around building a simple dApp while introducing the Brushfam tools. That way beginners can have an easy start in hacking.

**Comment by coreggon11** [comment]
Thanks for your responses!
@SkymanOne this was the original idea, I will update the proposal accordingly
@sacha-l this time works

**Comment by sacha-l** [comment]
How's this for a title and description?

Title: BrushFam: a tool suite for ink! smart contract developers

Description: In this seminar we will present the Brushfam tools suite, including OpenBrush, Typechain-polkadot and Sol2Ink. Towards the end, we will build a simple dApp showcasing these tools.

**Comment by coreggon11** [comment]
@sacha-l the description is good, the title I'd rather say `Brushfam's tool suite for ink! smart contract development`
