### ISSUE TITLE
Connecting to Rococo

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-seminar#4]
I suggest a seminar covering how to connect to the Rococo test network and how its maintainers have helped transition Rococo from being sudo controlled to community run. I imagine the following structure (roughly):

1. **Intro:** what's Rococo, what it's used for, how it's managed, historical context
2. **Rococo's runtime:** a closer look at onboarding pallets, how does it contrast from other test nets 
3. **Parachain registration process:** demo and explanation of how to add a chain to Rococo
4. **Next steps:**: questions, future steps, vision

Learning objectives:

- How to manage a test network
- How Rococo's registration system works
- How to connect your parachain to the Rococo test network

Any additional thoughts or ideas are welcome. I think it would benefit the community to have this seminar sooner than later because of how many teams may be interested in onboarding to Rococo. 

Some useful resources for context:

- https://docs.substrate.io/tutorials/v3/cumulus/rococo/
- https://medium.com/polkadot-network/rococo-revamp-becoming-a-community-parachain-testbed-fe1de1e855d1
- https://polkadot.network/introducing-rococo-polkadots-parachain-testnet/
- https://medium.com/polkadot-network/introducing-rococo-polkadots-parachain-testnet-e3e67fc40b56

**Comment by NukeManDan** [comment]
There will be updates to the onboarding flow relatively soon FYI - so this should wait till those are in place :pray: 
- [ ] https://github.com/paritytech/polkadot/pull/5130
- [ ] (more TBA on docs)

**Comment by sacha-l** [comment]
Ok this is good to know. Yes, we should come back to this topic once these updates are made :)

**Comment by sacha-l** [comment]
@NukeManDan any update on when we'll be able to cover this seminar?

**Comment by sacha-l** [comment]
Questions: 
- How would I perform a runtime upgrade on Rococo ?
- Do HRMP channels close once the 3 day period expires ? How does that work?
