### ISSUE TITLE
[Topic Proposal]: Tuxedo

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-seminar#40]
### Title

Tuxedo: Substrate Runtimes with the UTXO model

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Intermediate

### Description

In the blockchain space their are two main models for creating chain logic. The account model like in Ethereum and Polkadot, and the UTXO model like in Monero and Cardano.

Substrate runtimes have traditionally been written in FRAME which uses the account model. But Substrate itself is general enough to support either. Enter Tuxedo. Tuxedo is an alternative to FRAME that allows developers to write Substrate runtimes in the UTXO model.

cc @coax1d

### Topic

Runtime Development

### Plan

This Seminar will cover foundational concepts, discuss the UTXO model theory, live code a UTXO based runtime including unit tests with Tuxedo, and play with the resulting chain.

* Explore Substrate's client/runtime boundary
* Clarify that FRAME is just for the Runtime, has assumptions, and is not a necessary part of a Substrate Chain
* Compare and contrast the accounts model and the UTXO model
* Look at the Tuxedo architecture and Tuxedo template node
* Live code a Runtime using Tuxedo. (I'm thinking maybe an order-book dex or a TCR, but open to suggestions.)
* Start up and play with the resulting chain.

### Links and resources

Tuxedo repository: https://github.com/Off-Narrative-Labs/Tuxedo/
W3F Grant: https://github.com/w3f/Grants-Program/blob/master/applications/tuxedo.md

**Comment by sacha-l** [comment]
Sweet thanks for proposing this topic. Which Tuesday works best for you out of April 11, 18 or 25 (4PM CET) ? And would you like @coax1d to also present? I would love to co-host this one with @aaronbassett :)

**Comment by coax1d** [comment]
Would love to!

**Comment by laurenelee** [comment]
Hiya - So an update for folks! 
Sacha is going to pause hosting Seminars so that he can be heads down building some technical content and workshops. 
I'm going to pick up as host for Seminars moving forward. Does the 11th still work for you @JoshOrndorff and @coax1d to come on and talk about this? Same time and everything (10am EST/ 3pm UK time) - I can share a link to the platform we use to stream in just a moment! 
We could also do a pre-stream call just to double check mic and cameras and all of that! Will schedule that now if that works for you both🙌

**Comment by sacha-l** [comment]
Thanks for taking this one @laurenelee. @coax1d as you probably already know, you'll be in good hands with Lauren :)

I'll update the [scheduled seminar folder](https://github.com/substrate-developer-hub/substrate-seminar/tree/main/scheduled/2023) with the write up of this plan. Feel free to share it around for anyone you plan to invite to the stream on Tuesday, it'll go in the calendar link too. 

With that said, have a great stream - looking forward to learning about Tuxedo!
