### ISSUE TITLE
[Topic Proposal]: KILT Protocol 101

### ISSUE THREAD

**Issue by Dudleyneedham** [substrate-developer-hub/substrate-seminar#41]
### Title

KILT Protocol 101

### How advanced is this topic in terms of pre-requisite knowledge of Substrate?

Intermediate

### Description

A dive into KILT Protocol. Looking at the different features, including Decentralized Identifiers (DID), Verifiable Credentials and the different Actors in play. 

It will look at some new demos and show case some great usecases that can be used today and some that can be used in the future.

### Topic

KILT Protocol 101 - A glimpse into the past, present and future

### Plan

Part 1 - KILT Protocol history. A general discussion on where KILT started and what it has achieved.

Part 2 - What technology we currently have and what can be shown today for use inside and outside the eco-system

Part 3 - Where KILT is heading? What technology do we have for the future of digital identity in the Eco-system?

**Comment by sacha-l** [comment]
Amazing thanks for adding this in, I'll make sure to update the archive folder with this once we get the video link of the stream's recording. 🚀 

cc @laurenelee
