### ISSUE TITLE
An XCM-based high-level standard and interface (ABI) for smart contracts

### ISSUE THREAD

**Issue by t3rninator** [substrate-developer-hub/substrate-seminar#9]
The power of an XCM-based Binary Interface that extends the XCM-protocol to enable smart contracts calls, while receiving execution results back to the source Parachain. 

The same interface can be used to connect Smart Contract VMs installed on other Parachains, as well as to communicate with remote-to-Polkadot blockchains using the XCM protocol, which will be compatible with the bridges of the most active blockchain ecosystems today (i.e. Ethereum, Solana, Avalanche, Cosmos), how this will support the Polkadot ecosystem and what novel use cases it will enable

**Comment by sacha-l** [comment]
@t3rninator : can you share any links and resources about this ? Also, it isn't clear whether this is a proposal topic that you'd like to present, or if it's a topic you'd like to learn more about. Please elaborate 😃

**Comment by t3rninator** [comment]
Sure, apologies. So we (t3rn) would like to present what we have submitted to the Web3 Foundation for our second grant (having completed our first in December 2020). We are working on a new Polkadot Standard Proposal for an XCM-based high-level interface for cross-chain smart contract execution, known as XBI. 

XBI will be an XCM-based Binary Interface that extends the XCM-protocol to enable smart contracts calls, while receiving execution results back to the source Parachain. The same interface will be used to connect Smart Contract VMs installed on other Parachains, as well as to communicate with remote-to-Polkadot blockchains using the XCM protocol, which will be compatible with the bridges of the most active blockchain ecosystems today (i.e. Ethereum, Solana, Avalanche, Cosmos). We believe this is a positive step in furthering XCM adoption and utility.

**Comment by sacha-l** [comment]
Could you DM me so I can better understand what I may need to prepare for this / what resources we can share for others ? You can use Element: @sacha-l:matrix.parity.io

Cheers!

**Comment by t3rninator** [comment]
Hey Sacha,

Just touching base on this; we've had a lighter version of the talk
accepted for Polkadot Decoded and was wondering whether you would still
like us to present this, with more depth, as a Substrate Seminar.

Let me know if you'd still like for us to give a presentation.

Look forward to hearing from you.

Cheers,
Jacob

**Comment by sacha-l** [comment]
Hi @t3rninator - thank you for following up here. 

This is certainly a superb topic for seminar, especially how it highlights XCM the way it does. I would suggest we pick a date after Decoded, say July 5th or 19th? That way you can mention that you'll be going into more technical detail at the seminar and provide a deep dive into how it all works and demonstrate what you can do with it. Let me know which works best for you and Maciej and we'll pencil it into the calendar!

**Comment by t3rninator** [comment]
Hey Sacha,

Agreed, it sounds like a perfect fit.

5th July is preferable for us, if still available.

Let me know.

Cheers,
Jacob

**Comment by sacha-l** [comment]
@t3rninator: could you provide more details so that I can add this to the schedule, including (please fill in the blanks):

## Title

An XCM-based high-level standard and interface (ABI) for smart contracts

## Description

In this seminar, we will explore the power of an XCM-based Binary Interface that extends the XCM-protocol to enable smart contracts calls, while receiving execution results back to the source Parachain.


## Plan 

_(i.e. just the outline of your seminar)_

## Links and resources 

_(e.g. if you have a deck; repos where this work exists; related material; complimentary readings etc.)_

Thanks!

**Comment by sacha-l** [comment]
Hey @t3rninator - just a ping on this? 🙏🏻

**Comment by t3rninator** [comment]
Hey Sacha,

Apologies, I got taken down by covid; there was me naively thinking that it
was a thing of the past and our only worries these days were the markets.
Title

XBI: an XCM-based high-level standard and interface (ABI) for smart
contracts.
Description

In this seminar, we will explore the power of an XCM-based Binary Interface
that extends the XCM protocol to enable smart contract calls, explaining
why XCM is powerful but needs to be extended and detailing how XBI offers a
trail-blazing solution.
Plan


   - What is t3rn
      - Composing cross-chain smart contract execution.
   - Importance of trust-free bridging
      - The status quo
      - The problem
      - Different degrees of trust-free guarantees
   - What is XBI
      - How XBI improves XCM
   - How to use XBI

Links and resources
Our Web3 Foundation Grant Github
<https://github.com/t3rn/portal-xcm/pull/2/files#diff-aec638855addbe86e755d16744c9b9e751054d1cc4d3a620ce39a594ea1df092>.
We also have a private repo that we are working on XBI with the Moonbeam
and Astar teams that we might be able to make public for the seminar.

Let me know if this is sufficient and once again apologise for my slowness.

Cheers,
Jacob

**Comment by sacha-l** [comment]
Hey @t3rninator - no worries at all. 

Can you share the link to the original grant and any other readings you recommend that could prepare attendees to follow the seminar?

In:
> Our Web3 Foundation Grant Github
<https://github.com/t3rn/portal-xcm/pull/2/files#diff-aec638855addbe86e755d16744c9b9e751054d1cc4d3a620ce39a594ea1df092>.

... the link is giving me a 404, maybe because its private.

Logistical question: are you good to present this on July 5th ? Cheers!

**Comment by t3rninator** [comment]
Hey Sacha,

Apologies for that, this should be fine –
https://github.com/w3f/Grants-Program/blob/master/applications/xbi-format-psp-t3rn.md
<https://github.com/w3f/Grants-Program/blob/master/applications/xbi-format-psp-t3rn.md>

Regarding your logistical question, would it be possible at all to push the
seminar to a slightly later date; late July or early August?

We've had a sudden and somewhat unexpected pile-up of presentations/events
so it could be good to spread them out a bit, let me know what you think.

Cheers,
Jacob

**Comment by sacha-l** [comment]
How does August 16th work?

**Comment by t3rninator** [comment]
Perfect :)
